# SOURCE = "/home/razvandaraban/Projets/OC/Projet_03_OC/"
SOURCE = "./"
DATA = SOURCE + "data/"
PLAYER_FILE = DATA + "players.json"
TOURNAMENT_FILE = DATA + "tournaments.json"
ROUND_FILE = DATA + "rounds.json"
